services:
  
  database:
    image: 'postgres:15.3'
    container_name: my-app-postgres    
    environment:
        POSTGRES_DB: my-app
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - my-app-postgres-data:/var/lib/postgresql/data
      # - ./scripts/keycloak/init-database.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: "exit 0"

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-app-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - my-app-pgadmin4-data:/var/lib/pgadmin
      - ./scripts/pgadmin/servers.json:/pgadmin4/servers.json  
    depends_on:
      database:
        condition: service_healthy

volumes:
  my-app-postgres-data:
  my-app-pgadmin4-data:

networks:
  default:
    external: true
    name: development
